version: '3.1'
services:
  backend:
    image: maven:3.6.3-jdk-8
    command: mvn spring-boot:run
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/mymaven:rw
    working_dir: /usr/src/mymaven